### ISSUE TITLE
[BUG in slab.sound.calibrate]

### ISSUE THREAD

**Issue by sneakers-the-rat** [DrMarc/slab#22]
**Describe the bug**
`slab.sound.calibrate` exits with the following exception:

```
>>> slab.sound.calibrate()
Playing 1kHz test tone for 5 seconds. Please measure intensity.
Enter measured intensity in dB: >? 60
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/jonny/git/slab/slab/sound.py", line 1287, in calibrate
    intensity = intensity - tone.level  # subtract measured from rms intensity
numpy.core._exceptions._UFuncNoLoopError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
```

looks like you might need explicit type conversion? not sure.

slab version == 0.9.0
numpy version == 1.20.3
os == macOS 11.3.1

**Comment by hadware** [comment]
Same error here (running Ubuntu 20.04, with the following pip list:)

```
Package         Version
--------------- ------------
attrs           21.2.0
cffi            1.14.5
cycler          0.10.0
h5netcdf        0.11.0
h5py            3.2.1
iniconfig       1.1.1
kiwisolver      1.3.1
matplotlib      3.4.2
numpy           1.20.3
packaging       20.9
Pillow          8.2.0
pip             21.1.1
pkg-resources   0.0.0
pluggy          0.13.1
py              1.10.0
pycparser       2.20
pyparsing       2.4.7
pytest          6.2.4
python-dateutil 2.8.1
scipy           1.6.3
setuptools      44.0.0
six             1.16.0
slab            0.9.0
SoundFile       0.10.3.post1
toml            0.10.2
```

**Comment by DrMarc** [comment]
Hi, thanks for catching that! Resolved by type conversion. Also fixed the incorrect reference to slab.calibrate() in the docs.
